# Generated by Django 5.2.7 on 2026-01-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_title_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
