# Generated by Django 5.2.7 on 2025-11-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateanswer",
            name="code_answer",
            field=models.TextField(
                blank=True,
                help_text="Código escrito por el candidato (para preguntas de código)",
            ),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="answer_text",
            field=models.TextField(blank=True, help_text="Respuesta de texto"),
        ),
    ]
