# Generated by Django 5.2.7 on 2025-10-17 02:33

import django.db.models.deletion
import recruiting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=recruiting.models.cv_upload_path)),
                ('parsed_text', models.TextField(blank=True)),
                ('match_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW', 'In Review'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('candidate', 'project')},
            },
        ),
    ]
