# Generated by Django 5.2.7 on 2025-11-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extracted',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
